tap "felixkratz/formulae"
tap "koekeishiya/formulae"
tap "netmute/tap"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "qmk/qmk"
tap "shaunsingh/sfmono-nerd-font-ligaturized"
# Simple, modern, secure file encryption
brew "age"
# Code searching, linting, rewriting
brew "ast-grep"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Bash scripts that integrate bat with various command-line tools
brew "bat-extras"
# XML 1.0 parser
brew "expat"
# Interpreted, interactive, object-oriented programming language
brew "python@3.13"
# Python code formatter
brew "black"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Powerful, lightweight programming language
brew "lua"
# Elegant Lua unit testing
brew "busted"
# Versatile and fast Unicode/ASCII/ANSI graphics renderer
brew "chafa"
# General purpose syntax highlighter in pure Go
brew "chroma"
# Cross-platform make
brew "cmake"
# Documentation for CMake
brew "cmake-docs"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# General-purpose scripting language
brew "php", restart_service: :changed
# Dependency Manager for PHP
brew "composer"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Load/unload environment variables based on $PWD
brew "direnv"
# Text processing system for reStructuredText
brew "docutils"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Banner-like program prints strings as ASCII art
brew "figlet"
# Utility to determine file types
brew "file-formula"
# Indent and beautify Fortran sources and generate dependency information
brew "findent"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish", args: ["HEAD"]
# Command-line fuzzy finder written in Go
brew "fzf"
# Fast, simple fuzzy text selector with an advanced scoring algorithm
brew "fzy"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Blazing fast terminal-ui for git written in rust
brew "gitui"
# Render markdown on the CLI
brew "glow"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Post-modern modal text editor
brew "helix"
# Website copier/offline browser
brew "httrack"
# Add GitHub support to git on the command-line
brew "hub"
# Tools and libraries to manipulate images in many formats
brew "imagemagick"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Clean C library for processing UTF-8 Unicode data
brew "utf8proc", args: ["HEAD"]
# Fast, Dynamic Programming Language
brew "julia"
# Lazier way to manage everything docker
brew "lazydocker"
# Simple terminal UI for git commands
brew "lazygit"
# Curses-based tool for viewing and analyzing log files
brew "lnav"
# Rainbows and unicorns in your console!
brew "lolcat"
# Package manager for the Lua programming language
brew "luarocks"
# Platform built on V8 to build network applications
brew "node"
# Generate a markdown TOC (table of contents) with Remarkable
brew "markdown-toc"
# Fast, flexible, config-based cli for linting Markdown/CommonMark files
brew "markdownlint-cli2"
# Mac App Store command-line interface
brew "mas"
# Remote terminal application
brew "mosh"
# Tail multiple files in one terminal simultaneously
brew "multitail"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Modern shell for the GitHub era
brew "nushell"
# General purpose programming language in the ML family
brew "ocaml"
# Prompt theme engine for any shell
brew "oh-my-posh"
# Create, run, and share large language models (LLMs)
brew "ollama", link: false
# OCaml package manager
brew "opam"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Highly capable, feature-rich programming language
brew "perl"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# Fast, disk space efficient package manager
brew "pnpm"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Code formatter for JavaScript, CSS, JSON, GraphQL, Markdown, YAML
brew "prettier"
# Prettier daemon
brew "prettierd"
# Python version management
brew "pyenv"
# Generic syntax highlighter
brew "pygments"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Simple, modern, secure file encryption
brew "rage"
# Reattach process (e.g., tmux) to background
brew "reattach-to-user-namespace"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby"
# Safe, concurrent, practical language
brew "rust"
# Experimental Rust compiler front-end for IDEs
brew "rust-analyzer"
# Bash completion for rustc
brew "rustc-completion"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Autoformat shell script source code
brew "shfmt"
# Simple keystroke visualizer
brew "showkey"
# Tool to create intelligent and beautiful documentation
brew "sphinx-doc"
# SQL linter and auto-formatter for Humans
brew "sqlfluff"
# Modern and pretty fancy file manager for the terminal
brew "superfile"
# TUI to view and query tabular files (CSV,TSV, Parquet, etc.)
brew "tabiew"
# Feature-rich console based todo list manager
brew "task"
# Tool for taking notes and open urls with taskwarrior
brew "taskopen"
# Terminal user interface for taskwarrior
brew "taskwarrior-tui"
# General purpose fuzzy finder TUI
brew "television"
# TUI interface for LLMs written in Rust
brew "tenere"
# Code-search similar to ack
brew "the_silver_searcher"
# Command-line time tracking application
brew "timewarrior"
# Terminal multiplexer
brew "tmux"
# Lightweight BitTorrent client
brew "transmission-cli", restart_service: :changed
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Network diagnostic tool, inspired by mtr
brew "trippy"
# Maintained ctags implementation
brew "universal-ctags"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Simple terminal image viewer written in Rust
brew "viu"
# Test compatibility of VT100-compatible terminals
brew "vttest"
# Internet file retriever
brew "wget"
# Lexical database for the English language
brew "wordnet"
# Access X11 clipboards from the command-line
brew "xclip"
# Command-line program for getting and setting the contents of the X selection
brew "xsel"
# JavaScript package manager
brew "yarn"
# Blazing fast terminal file manager written in Rust, based on async I/O
brew "yazi"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Compression and file packaging/archive utility
brew "zip"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Feature-rich syntax highlighting for Zsh
brew "zsh-fast-syntax-highlighting"
# Zsh port of Fish shell's history search
brew "zsh-history-substring-search"
# Better and friendly vi(vim) mode plugin for ZSH
brew "zsh-vi-mode"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
# LSP implementation using universal-ctags as backend
brew "netmute/tap/ctags-lsp"
# GNU compiler collection for AVR 8-bit and 32-bit Microcontrollers
brew "osx-cross/avr/avr-gcc@8"
# Quantum Mechanical Keyboard (QMK) Firmware
brew "qmk/qmk/qmk"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
# View, print, and comment on PDF documents
cask "adobe-acrobat-reader"
# Application launcher and productivity software
cask "alfred"
# Local-first and end-to-end encrypted notes app
cask "anytype"
# Data backup and storage service
cask "backblaze"
# Edit and manage bibliographies
cask "bibdesk"
# E-books management software
cask "calibre"
# Synchronisation and backup tool
cask "chronosync"
# GUI companion app for Homebrew
cask "cork"
# Disk space visualiser
cask "daisydisk"
# Assistant for efficient web searches
cask "devonagent"
# Collect, organise, edit and annotate documents
cask "devonthink"
# Voice and text chat software
cask "discord"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Launcher for *Epic Games* games
cask "epic-games"
# Cross-platform Text Expander written in Rust
cask "espanso"
# Web browser
cask "firefox"
cask "font-hack-nerd-font"
# SFMono with Nerd Font Glyphs and Fira Code Ligatures
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-symbols-only-nerd-font"
# GIT client
cask "fork"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Free and open-source image editor
cask "gimp"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Grammarly for desktop
cask "grammarly-desktop"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Optimise and personalise your Jabra headset
cask "jabra-direct"
# Menu bar manager
cask "jordanbaird-ice"
# Keyboard customiser
cask "karabiner-elements"
# Automation software
cask "keyboard-maestro"
# Finds, learns and remembers keyboard shortcuts
cask "keycue"
# Graphical interface for LaTeX
cask "latexit"
# Software for Logitech devices
cask "logi-options+"
# Privacy-first, open-source platform for knowledge sharing and management
cask "logseq"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Minimal installer for conda
cask "miniconda"
# Spotlight Search
cask "monarch"
# Utility to move and zoom windows—on one display
cask "moom"
# Desktop sync client for Nextcloud software products
cask "nextcloud"
# App to write, plan, collaborate, and get organised
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Get up and running with large language models locally
cask "ollama"
# Interact with Ollama models
cask "ollamac"
# Scheduling application focusing on organisation
cask "omnifocus"
# Visual communication software
cask "omnigraffle"
# Note taking application and information organiser
cask "omnioutliner"
# Project planning and management software
cask "omniplan"
# Desktop virtualization software
cask "parallels"
# Bundle with over 30 tools
cask "parallels-toolbox"
# RPN calculator based on HP-42S
cask "plus42-decimal"
# Toolbox companion for QMK Firmware
cask "qmk-toolbox"
# Collection of apps available by subscription
cask "setapp"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# Screen capture software
cask "snagit"
# Sound and audio controller
cask "soundsource"
# Spam filtering extension for e-mail clients
cask "spamsieve"
# Video game digital distribution service
cask "steam"
# Spreadsheet style tag editor for audio files
cask "tageditor"
# Graphical user interface for TeX Live Manager
cask "tex-live-utility"
# LaTeX and TeX editor and previewer
cask "texshop"
# Customizable email client
cask "thunderbird"
# Charting and social-networking for investment traders
cask "tradingview"
# Open-source BitTorrent client
cask "transmission"
# File transfer application
cask "transmit"
# Companion app for the Trezor hardware wallet
cask "trezor-suite"
# Keyboard configurator
cask "via"
# Multimedia player
cask "vlc"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Window manager
cask "wins"
# Multiplayer code editor
cask "zed"
# Gecko based web browser
cask "zen-browser"
